base_url = "https://maciejpedzich-preview.onrender.com"
compile_sass = true
title = "Maciej Pędzich"
description = "Computer Science student @ PJAIT. F1 nerd since birth. Avid homelabber. House music aficionado. Visibly on the spectrum. Warsaw. he/him."
theme = "tabi"
default_language = "en"
taxonomies = [{ name = "tags", feed = true }]
build_search_index = true
generate_feeds = true

[markdown]
highlight_code = true
bottom_footnotes = true
highlight_theme = "css"

[extra]
skin = "custom"
browser_theme_color = "#cd3731"
favicon = "images/favicon.png"
social_media_card = "/images/banner.png"
show_author = false
toc = true
quick_navigation_buttons = true
stylesheets = ["css/custom.css"]
menu = [
  { name = "Blog", url = "blog" },
  { name = "Tags", url = "tags" },
  { name = "Archive", url = "archive" },
]
socials = [
  { name = "Email", url = "mailto:contact@maciejpedzi.ch", icon = "email" },
  { name = "Gitea", url = "https://code.maciejpedzi.ch", icon = "gitea" },
  { name = "GitHub", url = "https://github.com/maciejpedzich", icon = "github" },
  { name = "Bluesky", url = "https://bsky.app/profile/maciejpedzi.ch", icon = "bluesky" },
  { name = "LinkedIn", url = "https://www.linkedin.com/in/maciejpedzich", icon = "linkedin" },
]
copyright = "© $CURRENT_YEAR Maciej Pędzich $SEPARATOR Content on this website is available under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0) license."
