base_url = "https://maciejpedzi.ch"
compile_sass = true
title = "Maciej Pędzich"
description = "Computer Science student @ PJAIT. F1 nerd since birth. Avid homelabber. House music aficionado. Visibly on the spectrum. Warsaw. he/him."
theme = "tabi"
default_language = "en"
taxonomies = [{ name = "tags", feed = true }]
build_search_index = true
generate_feeds = true

[markdown]
highlight_code = true
bottom_footnotes = true
highlight_theme = "css"

[extra]
skin = "custom"
browser_theme_color = "#c63839"
favicon = "images/favicon.png"
social_media_card = "/images/banner.png"
show_author = false
feed_icon = false
toc = true
quick_navigation_buttons = true
stylesheets = ["css/custom.css"]
menu = [
  { name = "Blog", url = "blog" },
  { name = "Tags", url = "tags" },
  { name = "Archive", url = "archive" },
]
socials = [
  { name = "Atom feed", url = "/atom.xml", icon = "rss" },
  { name = "Email", url = "mailto:contact@maciejpedzi.ch", icon = "email" },
  { name = "Gitea", url = "https://code.maciejpedzi.ch", icon = "gitea" },
  { name = "GitHub", url = "https://github.com/maciejpedzich", icon = "github" },
  { name = "Bluesky", url = "https://bsky.app/profile/maciejpedzi.ch", icon = "bluesky" },
  { name = "LinkedIn", url = "https://www.linkedin.com/in/maciejpedzich", icon = "linkedin" },
]
footer_menu = [
  { url = "https://analytics.maciejpedzi.ch/share/U4Mdaexoe2kqAnrS/maciejpedzi.ch", name = "Analytics", trailing_slash = false },
  { url = "/pubkey.asc", name = "PGP key", trailing_slash = false },
  { url = "/privacy", name = "Privacy", trailing_slash = false },
  { url = "/sitemap.xml", name = "Sitemap", trailing_slash = false },
]
copyright = "© $CURRENT_YEAR Maciej Pędzich $SEPARATOR Content on this website is available under the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0) license."
remote_repository_url = "https://code.maciejpedzi.ch/maciejpedzich/website"
remote_repository_git_platform = "gitea"
remote_repository_branch = "master"
show_remote_changes = true
show_remote_source = true

[extra.analytics]
service = "umami"
self_hosted_url = "https://analytics.maciejpedzi.ch"
id = "108f9ca1-3178-4553-862b-150298be719e"
do_not_track = true
